# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hopt < Formula
  desc "A TUI to interact with The Hoptimist store"
  homepage "https://github.com/matt-riley/hopcli"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/matt-riley/hopcli/releases/download/v0.0.2/hopt_Darwin_x86_64.tar.gz"
      sha256 "8a9ce337c867d94c7413a14898987448ab6bc20883bba4eda18384ed1b6e7a28"

      def install
        bin.install "hopt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/matt-riley/hopcli/releases/download/v0.0.2/hopt_Darwin_arm64.tar.gz"
      sha256 "9152b859395c7b3ed9d9d9959f94a5984d697c58ee2525269727672ab94691d4"

      def install
        bin.install "hopt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/matt-riley/hopcli/releases/download/v0.0.2/hopt_Linux_arm64.tar.gz"
      sha256 "d1817e428660ad91d8da99ac0555ab7bcd8633db24112f6596cd78a327416142"

      def install
        bin.install "hopt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/matt-riley/hopcli/releases/download/v0.0.2/hopt_Linux_x86_64.tar.gz"
      sha256 "a1e1dc450e8bc726a8ff80d649e2b11caf52b4eab9fbb4e07271b1d676820dcc"

      def install
        bin.install "hopt"
      end
    end
  end
end
