# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hopt < Formula
  desc "A TUI to interact with The Hoptimist store"
  homepage "https://github.com/matt-riley/hopcli"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/matt-riley/hopcli/releases/download/v0.0.1/hopt_Darwin_x86_64.tar.gz"
      sha256 "ece08442f7ddc8889ce5e3d458eda5dd946154de3ae45683ab7106dbd91a58a4"

      def install
        bin.install "hopt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/matt-riley/hopcli/releases/download/v0.0.1/hopt_Darwin_arm64.tar.gz"
      sha256 "e2d22a2e65be3c73a7b40f014b4d7d61408653ef13a3c01851c8a64aac1b462f"

      def install
        bin.install "hopt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/matt-riley/hopcli/releases/download/v0.0.1/hopt_Linux_arm64.tar.gz"
      sha256 "9782654a009c8aaf9e223b7a1b41b187e35e538dabb0db1e81665d23ee87f4fa"

      def install
        bin.install "hopt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/matt-riley/hopcli/releases/download/v0.0.1/hopt_Linux_x86_64.tar.gz"
      sha256 "cc997e554549901d3fdb87b2ac60837afccb23aeeee0513b381574922a4ea6ee"

      def install
        bin.install "hopt"
      end
    end
  end
end
