# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mattd < Formula
  desc "A simple tool to grab my dots and setup a new machine"
  homepage "https://github.com/matt-riley/dots-cli"
  version "0.0.9"

  depends_on "atuin"
  depends_on "bat"
  depends_on "curl"
  depends_on "fzf"
  depends_on "gh"
  depends_on "git"
  depends_on "jq"
  depends_on "lsd"
  depends_on "navi"
  depends_on "ripgrep"
  depends_on "rtx"
  depends_on "starship"
  depends_on "stow"
  depends_on "tmux"
  depends_on "wakatime-cli"
  depends_on "wget"
  depends_on "zoxide"
  depends_on "zplug"
  depends_on "zsh"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/matt-riley/dots-cli/releases/download/v0.0.9/mattd_Darwin_arm64.tar.gz"
      sha256 "9a36e72d5dce30f76a440ec592b155639eec3caee0aa3f6f2fa6407f2c2ad396"

      def install
        bin.install "mattd"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/matt-riley/dots-cli/releases/download/v0.0.9/mattd_Darwin_x86_64.tar.gz"
      sha256 "a8110a406289c95cad266bd112554281c804b19f1892ad2b10d492e8510c859d"

      def install
        bin.install "mattd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/matt-riley/dots-cli/releases/download/v0.0.9/mattd_Linux_arm64.tar.gz"
      sha256 "c38867562a28c12f1a0448c36c6a41fb0c66dc284eb9e85fe9105b1bb03f9687"

      def install
        bin.install "mattd"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/matt-riley/dots-cli/releases/download/v0.0.9/mattd_Linux_x86_64.tar.gz"
      sha256 "2bbc3860effc75c1f458d2b6afe0e49ad132856bb84adc4bb46d8befb87e0e6f"

      def install
        bin.install "mattd"
      end
    end
  end
end
