# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mattd < Formula
  desc "A simple tool to grab my dots and setup a new machine"
  homepage "https://github.com/matt-riley/dots-cli"
  version "0.0.4"

  depends_on "atuin"
  depends_on "bat"
  depends_on "curl"
  depends_on "fzf"
  depends_on "gh"
  depends_on "git"
  depends_on "jq"
  depends_on "lsd"
  depends_on "navi"
  depends_on "ripgrep"
  depends_on "rtx"
  depends_on "starship"
  depends_on "stow"
  depends_on "tmux"
  depends_on "wakatime-cli"
  depends_on "wget"
  depends_on "zoxide"
  depends_on "zplug"
  depends_on "zsh"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/matt-riley/dots-cli/releases/download/v0.0.4/mattd_Darwin_arm64.tar.gz"
      sha256 "205ed9fae44dc8d189462eed55dc4bd4462a171f0297824bd739f20a124ad0ea"

      def install
        bin.install "mattd"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/matt-riley/dots-cli/releases/download/v0.0.4/mattd_Darwin_x86_64.tar.gz"
      sha256 "613cb22a57c04447660f91064f1358b6639019a088b19948dcf2c52cc8d8eb3b"

      def install
        bin.install "mattd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/matt-riley/dots-cli/releases/download/v0.0.4/mattd_Linux_arm64.tar.gz"
      sha256 "5a367db6a0a73753d9927784c93675b6bd34dcc987c5583e613ead3f374e06e8"

      def install
        bin.install "mattd"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/matt-riley/dots-cli/releases/download/v0.0.4/mattd_Linux_x86_64.tar.gz"
      sha256 "8b8514da74cbddadcbfef0b181e26e29977247728122402f9d9a88501b277230"

      def install
        bin.install "mattd"
      end
    end
  end
end
