# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mattd < Formula
  desc "A simple tool to grab my dots and setup a new machine"
  homepage "https://github.com/matt-riley/dots-cli"
  version "0.0.3"

  depends_on "atuin"
  depends_on "bat"
  depends_on "curl"
  depends_on "fzf"
  depends_on "gh"
  depends_on "git"
  depends_on "jq"
  depends_on "lsd"
  depends_on "navi"
  depends_on "ripgrep"
  depends_on "rtx"
  depends_on "starship"
  depends_on "stow"
  depends_on "tmux"
  depends_on "wakatime-cli"
  depends_on "wget"
  depends_on "zoxide"
  depends_on "zplug"
  depends_on "zsh"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/matt-riley/dots-cli/releases/download/v0.0.3/mattd_Darwin_x86_64.tar.gz"
      sha256 "8ea4e48d41831461fcae3f4699f6b22535deda4c31b641f75445682bc9a27752"

      def install
        bin.install "mattd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/matt-riley/dots-cli/releases/download/v0.0.3/mattd_Darwin_arm64.tar.gz"
      sha256 "19d5208777d33c84a476085358ae3a9cd6fd9f848e8787a5ddc3d32feb2fa377"

      def install
        bin.install "mattd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/matt-riley/dots-cli/releases/download/v0.0.3/mattd_Linux_x86_64.tar.gz"
      sha256 "be170fcc5c48599a4c968ec5151ae9651236cb28fb130efbadff5bf6464f523e"

      def install
        bin.install "mattd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/matt-riley/dots-cli/releases/download/v0.0.3/mattd_Linux_arm64.tar.gz"
      sha256 "a7ff2ea3daf3fbea2f48648e0a4522d79bb7459c91e18fdb966d21471c1c05a3"

      def install
        bin.install "mattd"
      end
    end
  end
end
