# This file was generated by GoReleaser. DO NOT EDIT.
cask "hopt" do
  name "hopt"
  desc "A TUI to interact with The Hoptimist store"
  homepage "https://github.com/matt-riley/hopcli"
  version "0.2.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hopt"

  on_macos do
    on_intel do
      url "https://github.com/matt-riley/hopcli/releases/download/v#{version}/hopt_Darwin_x86_64.tar.gz",
        verified: "github.com/matt-riley/hopcli"
      sha256 "e26c1f15747bd7c01491c654b4f28f5d5fba70865bbe1bf5d08125376d808ac6"
    end
    on_arm do
      url "https://github.com/matt-riley/hopcli/releases/download/v#{version}/hopt_Darwin_arm64.tar.gz",
        verified: "github.com/matt-riley/hopcli"
      sha256 "3b38a5d66508d3f0c9e683efa78b2437383e8ef8898544a46acf64032902b7cf"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/matt-riley/hopcli/releases/download/v#{version}/hopt_Linux_x86_64.tar.gz",
        verified: "github.com/matt-riley/hopcli"
      sha256 "33b5ca4cf13f476c17850333cab03730fcefe4633d203e6c0b0ad602e36a30c4"
    end
    on_arm do
      url "https://github.com/matt-riley/hopcli/releases/download/v#{version}/hopt_Linux_arm64.tar.gz",
        verified: "github.com/matt-riley/hopcli"
      sha256 "7d50c677dedfafbb3f42184dce6d21b29f8b487c993b03986fbca36b97943ce0"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hopt"]
    end
  end

  # No zap stanza required
end
