# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hopt < Formula
  desc "A TUI to interact with The Hoptimist store"
  homepage "https://github.com/matt-riley/hopcli"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/matt-riley/hopcli/releases/download/v0.2.0/hopt_Darwin_x86_64.tar.gz"
      sha256 "995781ecf176dde34e1b63482f4770cf0fdc94b30f4fd8b16db4d32015a4f1d2"

      def install
        bin.install "hopt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/matt-riley/hopcli/releases/download/v0.2.0/hopt_Darwin_arm64.tar.gz"
      sha256 "d305ae8c41af2df6fa84ab0bd0b27a4145318de407081904b465209b02fdf9e2"

      def install
        bin.install "hopt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/matt-riley/hopcli/releases/download/v0.2.0/hopt_Linux_x86_64.tar.gz"
      sha256 "8c9ab2d9097b55debc4a03d97eeec6044a0906cc16561c581501552b944340ed"

      def install
        bin.install "hopt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/matt-riley/hopcli/releases/download/v0.2.0/hopt_Linux_arm64.tar.gz"
      sha256 "a49ec937e447503fe597e78da0f802c3c1548463322cf5f27a04103c763b727c"

      def install
        bin.install "hopt"
      end
    end
  end
end
