# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Liner < Formula
  desc "Publish Markdown blog posts to mattriley.work via lexi's write API"
  homepage "https://github.com/matt-riley/liner"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/matt-riley/liner/releases/download/v1.0.0/liner_Darwin_x86_64.tar.gz"
      sha256 "56a8cdd56f4a57ef9052e43dbea4e6a1a8cce73b71a099b6b5379f2c0049b433"

      define_method(:install) do
        bin.install "liner"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/matt-riley/liner/releases/download/v1.0.0/liner_Darwin_arm64.tar.gz"
      sha256 "a1cfa140151b22c88173a4fa70e879eef6710564d5123218e4ebff54db0a2086"

      define_method(:install) do
        bin.install "liner"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/matt-riley/liner/releases/download/v1.0.0/liner_Linux_x86_64.tar.gz"
      sha256 "10d4e419109c64fab22277fa9deda304c40831e8bd4d7282fd55716071a62094"
      define_method(:install) do
        bin.install "liner"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/matt-riley/liner/releases/download/v1.0.0/liner_Linux_arm64.tar.gz"
      sha256 "f5e86d4a54bd9ac47658a29da32d3cd9656756d2749cfc43ba5a969ae42374f2"
      define_method(:install) do
        bin.install "liner"
      end
    end
  end
end
