# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mediacreator < Formula
  desc "Generate media via fal.ai and kie.ai from the CLI and save it to disk"
  homepage "https://github.com/matt-riley/mediacreator"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/matt-riley/mediacreator/releases/download/v0.2.0/mediacreator_0.2.0_darwin_amd64.tar.gz"
      sha256 "8512337c6d1cb211f24805cbfb847c4ae744d433abac36f65b6f6f9b1e3b2ce6"

      define_method(:install) do
        bin.install "mediacreator"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/matt-riley/mediacreator/releases/download/v0.2.0/mediacreator_0.2.0_darwin_arm64.tar.gz"
      sha256 "5eca53e54962373050fab6fb7352f13554724ec231e40a9ca17866ab3dc7ae51"

      define_method(:install) do
        bin.install "mediacreator"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/matt-riley/mediacreator/releases/download/v0.2.0/mediacreator_0.2.0_linux_amd64.tar.gz"
      sha256 "2579eda5f18005e128d841aa917ba05030f9643dc4791d9b549cc18afb304b2a"
      define_method(:install) do
        bin.install "mediacreator"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/matt-riley/mediacreator/releases/download/v0.2.0/mediacreator_0.2.0_linux_arm64.tar.gz"
      sha256 "7c4f094c64ca69f8ac04cf5fd5184bc8cbf82cd9ecd1b87ed4c212f5e35dc6ec"
      define_method(:install) do
        bin.install "mediacreator"
      end
    end
  end
end
