# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mediacreator < Formula
  desc "Generate media via fal.ai and kie.ai from the CLI and save it to disk"
  homepage "https://github.com/matt-riley/mediacreator"
  version "0.3.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/matt-riley/mediacreator/releases/download/v0.3.1/mediacreator_0.3.1_darwin_amd64.tar.gz"
      sha256 "6183f329a455defcfe573506ee0212baeebb15526b070f7da30b4a94e3ca1c7d"

      define_method(:install) do
        bin.install "mediacreator"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/matt-riley/mediacreator/releases/download/v0.3.1/mediacreator_0.3.1_darwin_arm64.tar.gz"
      sha256 "cb5c79496fc5734c3728d9b078a9454b25d031bda54a1c27d460ea292d133a7c"

      define_method(:install) do
        bin.install "mediacreator"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/matt-riley/mediacreator/releases/download/v0.3.1/mediacreator_0.3.1_linux_amd64.tar.gz"
      sha256 "ce7d47dc7f1d27ca9e761324c31df96e538cc9c264e446f8c1b0eea10bdbf86f"
      define_method(:install) do
        bin.install "mediacreator"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/matt-riley/mediacreator/releases/download/v0.3.1/mediacreator_0.3.1_linux_arm64.tar.gz"
      sha256 "0861196d61c99899cbf7cc98f311df6582fd522ec77178de463e975af202b167"
      define_method(:install) do
        bin.install "mediacreator"
      end
    end
  end
end
