# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Newbrew < Formula
  desc "Browse and inspect new Homebrew formulae from your terminal"
  homepage "https://github.com/matt-riley/newbrew"
  version "0.4.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/matt-riley/newbrew/releases/download/v0.4.1/newbrew_0.4.1_darwin_amd64.tar.gz"
      sha256 "898e5c0ff1f1741f845ea974a379acbde5861f3d51250b91cf2c51daa424c185"

      define_method(:install) do
        bin.install "newbrew"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/matt-riley/newbrew/releases/download/v0.4.1/newbrew_0.4.1_darwin_arm64.tar.gz"
      sha256 "4b65b2fab9c91cc456e8d4a8a06b491193bc92215a72a291547845232ff4c0eb"

      define_method(:install) do
        bin.install "newbrew"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/matt-riley/newbrew/releases/download/v0.4.1/newbrew_0.4.1_linux_amd64.tar.gz"
      sha256 "148151c8327bf5bd6c30e8f3aa055ba602d85a25d1984520223a8afcfef42808"
      define_method(:install) do
        bin.install "newbrew"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/matt-riley/newbrew/releases/download/v0.4.1/newbrew_0.4.1_linux_arm64.tar.gz"
      sha256 "086b51fd0563d1a4b99191c36031f9987cb701d76b96183568cc52bb18fb6908"
      define_method(:install) do
        bin.install "newbrew"
      end
    end
  end
end
