# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Newbrew < Formula
  desc "Browse and inspect new Homebrew formulae from your terminal"
  homepage "https://github.com/matt-riley/newbrew"
  version "0.1.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/matt-riley/newbrew/releases/download/v0.1.6/newbrew_0.1.6_darwin_amd64.tar.gz"
      sha256 "2967eaf533e13662c65507e154fd954af93d18fdc093203429873f0b9da15c74"

      define_method(:install) do
        bin.install "newbrew"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/matt-riley/newbrew/releases/download/v0.1.6/newbrew_0.1.6_darwin_arm64.tar.gz"
      sha256 "3fb81518f213d48143831d895b1a0dd69f341f342876496c7d9864ee500be021"

      define_method(:install) do
        bin.install "newbrew"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/matt-riley/newbrew/releases/download/v0.1.6/newbrew_0.1.6_linux_amd64.tar.gz"
      sha256 "04b4c0b3c6a05c219c4bbdbf223be37c0de17e9aa45611822372eb4e83c9c81d"
      define_method(:install) do
        bin.install "newbrew"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/matt-riley/newbrew/releases/download/v0.1.6/newbrew_0.1.6_linux_arm64.tar.gz"
      sha256 "5a03b177ed6112925710f949ab9e1d3b9c5b8410e2195083c7588d398b3cad08"
      define_method(:install) do
        bin.install "newbrew"
      end
    end
  end
end
