# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Newbrew < Formula
  desc "Browse and inspect new Homebrew formulae from your terminal"
  homepage "https://github.com/matt-riley/newbrew"
  version "0.1.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/matt-riley/newbrew/releases/download/v0.1.3/newbrew_0.1.3_darwin_amd64.tar.gz"
      sha256 "4b4a397bb9cddec887b90d15ec0faf6450e70d77074a2311892bc1b26798a9e6"

      define_method(:install) do
        bin.install "newbrew"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/matt-riley/newbrew/releases/download/v0.1.3/newbrew_0.1.3_darwin_arm64.tar.gz"
      sha256 "595805e9577a673f5c060fbf7b95a4f8dfacfdf4072f4fc7958c9e71dffe50a6"

      define_method(:install) do
        bin.install "newbrew"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/matt-riley/newbrew/releases/download/v0.1.3/newbrew_0.1.3_linux_amd64.tar.gz"
      sha256 "bcd179cde9ac48a1261b734a05fdbb00f705b26bb76aa451f1edcf79f452d8a2"
      define_method(:install) do
        bin.install "newbrew"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/matt-riley/newbrew/releases/download/v0.1.3/newbrew_0.1.3_linux_arm64.tar.gz"
      sha256 "e64a4d3021bc1e2abc0c41cbea23f69edfc2b8222c96121816ab6b2cd1e475b3"
      define_method(:install) do
        bin.install "newbrew"
      end
    end
  end
end
