# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tui < Formula
  desc "Workv2 terminal UI"
  homepage "https://github.com/matt-riley/workv2"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/matt-riley/workv2/releases/download/v0.2.1/tui_0.2.1_darwin_amd64.tar.gz"
      sha256 "f32d8a66f86ca75cd2bd2f7a7c5d4c72377dc1b3ab334fcdca75fc013b7ced9a"

      define_method(:install) do
        bin.install "mattriley"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/matt-riley/workv2/releases/download/v0.2.1/tui_0.2.1_darwin_arm64.tar.gz"
      sha256 "ffab9717ff8211011479b08ed48622d9d7c6d6e2383c2d09caa2c69b2e9d7316"

      define_method(:install) do
        bin.install "mattriley"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/matt-riley/workv2/releases/download/v0.2.1/tui_0.2.1_linux_amd64.tar.gz"
      sha256 "5d9ae7ea1cb50670cf2d70783cd50f8c96efd0b7b7f45c06648cd4f632bfe78b"
      define_method(:install) do
        bin.install "mattriley"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/matt-riley/workv2/releases/download/v0.2.1/tui_0.2.1_linux_arm64.tar.gz"
      sha256 "9034282dbd1ea92d48d954900acdc65fbf7d346517fca930695ab98858d3cc6f"
      define_method(:install) do
        bin.install "mattriley"
      end
    end
  end

  test do
    system "#{bin}/mattriley", "--help"
  end
end
