# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tui < Formula
  desc "Workv2 terminal UI"
  homepage "https://github.com/matt-riley/workv2"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/matt-riley/workv2/releases/download/v0.2.1/tui_0.2.1_darwin_amd64.tar.gz"
      sha256 "11623f689ea747ccf42ab92369dcabcee721924c5d5364f77717c09f92f00337"

      define_method(:install) do
        bin.install "mattriley"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/matt-riley/workv2/releases/download/v0.2.1/tui_0.2.1_darwin_arm64.tar.gz"
      sha256 "d8910826db6bd693cf157f5d74f8bb25bf6195b400bb15a2aabe21994e0c8904"

      define_method(:install) do
        bin.install "mattriley"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/matt-riley/workv2/releases/download/v0.2.1/tui_0.2.1_linux_amd64.tar.gz"
      sha256 "481b66cc0b8475e75637c03fe0bbd11420d0026ea8737baf4da5ea01da52fcf0"
      define_method(:install) do
        bin.install "mattriley"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/matt-riley/workv2/releases/download/v0.2.1/tui_0.2.1_linux_arm64.tar.gz"
      sha256 "c83d54ab9964371067d6956057285f5a447c189a35668acaede63f137f4876a7"
      define_method(:install) do
        bin.install "mattriley"
      end
    end
  end

  test do
    system "#{bin}/mattriley", "--help"
  end
end
